[project]
name = "vk-redirect-telegram"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
    "telebot>=0.0.5",
    "vk-api>=11.9.9",
    "yt-dlp>=2025.4.30",
]
